version: '3.4'
services:
   react-app:
      image: bilingual
      container_name: bilingual
      restart: always
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '80:80'
